apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-weather
    type: web
  name: api-weather
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3002
  selector:
    app: api-weather
    type: web
---
